services:
  postgres:
    image: postgres:16
    container_name: postgres
    networks: [cloud-net]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  order-service:
    image: order-service:dev
    container_name: order-service
    networks: [cloud-net]
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/orderdb
      SPRING_DATASOURCE_USERNAME: order_user
      SPRING_DATASOURCE_PASSWORD: orderpass

      SPRING_FLYWAY_SCHEMAS: orders
      SPRING_FLYWAY_DEFAULT_SCHEMA: orders
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: orders
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  cloud-net:
    driver: bridge

volumes:
  pg_data:
